### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by albersonmiranda** [giacomogroppi/writernote-qt#12]
Hi there!

Came across this project looking for an alternative to rnote, and was trying to contribute to a textbox feature. But I noticed that there's a lot of source file missing from directory.

Is there a specific commit that I should take as starting point?

**Comment by giacomogroppi** [comment]
Hi, originally this repository contained both the model, controller, and view components, and it was all based on using Qt as the framework. Now, since I wanted to also bring the project to Android and iOS natively, I completely separated the model from the view, leaving only the model here. The view for Linux, implemented in QML, is now inside giacomogroppi/writernote-desktop-ui. I forgot to update the documentation here
To develop, you need to download the 'view' and 'writernote-qt', and link the 'src' folder of 'writernote' into 'writernote-desktop-ui/src/model
